openapi: 3.0.0
info:
  version: 1.0.0
  title: fixtures for runtime test
paths: {}
components:
  schemas:
    NullableTarget:
      type: string
      nullable: true
    TestTarget:
      type: string
    TestObject:
      type: object
      additionalProperties: true
      properties:
        immediate:
          $ref: '#/components/schemas/TestTarget'
        inArray:
          type: array
          items:
            $ref: '#/components/schemas/TestTarget'
        booleanFlagg:
          type: boolean
        noHit:
          type: string
        recursive:
          $ref: '#/components/schemas/TestObject'
        recursiveInArray:
          type: 'array'
          items:
            $ref: '#/components/schemas/TestObject'
        nullable:
          $ref: '#/components/schemas/NullableTarget'
